ekf_filter_node:
  ros__parameters:
    use_sim_time: false
    two_d_mode: true
    map_frame: "map"
    odom_frame: "odom"
    base_link_frame: "base_link"
    world_frame: "odom"
    frequency: 30.0
    sensor_timeout: 0.1
    transform_timeout: 0.1
    transform_tolerance: 0.1

    imu0: /imu/data
    imu0_config: [false, false, false,
                  true, true, true,
                  false, false, false,
                  false, false, true,
                  true, true, true]
    imu0_differential: false
    imu0_relative: true
    imu0_queue_size: 10
